from typing import Final

class OHLCs:
    @staticmethod
    def __new__(*args, **kwargs) -> OHLCs: ...
    def __lt__(self, value): ...
    def __init__(self, *args, **kwargs): ...
    def __hash__(self): ...
    def __eq__(self, value): ...

class Signal:
    @property
    def index(self): ...
    @property
    def order_type(self): ...
    @property
    def side(self): ...
    @property
    def signal_type(self): ...
    @staticmethod
    def __new__(*args, **kwargs) -> Signal: ...
    def __lt__(self, value): ...
    def __init__(self, *args, **kwargs): ...
    def __hash__(self): ...
    def __eq__(self, value): ...

